
import requests

# url = 'http://jjj.bio.vu.nl/rest/models'
#
# response = requests.get(url)
# response = response.json()
#
# # for each in response:
# #     print(each)
#
# sbml_addresses = []
#
# for each in response:
#     # print(each['details'])
#     sbml_addresses.append(each['details'] + 'sbml')

# sbml_files = [
#     'https://jjj.bio.vu.nl/rest/models/abudukelimu1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/achcar1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/achcar10/sbml',
#     'https://jjj.bio.vu.nl/rest/models/achcar11/sbml',
#     'https://jjj.bio.vu.nl/rest/models/achcar12/sbml',
#     'https://jjj.bio.vu.nl/rest/models/achcar13/sbml',
#     'https://jjj.bio.vu.nl/rest/models/achcar14/sbml',
#     'https://jjj.bio.vu.nl/rest/models/achcar2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/achcar3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/achcar4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/achcar5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/achcar6/sbml',
#     'https://jjj.bio.vu.nl/rest/models/achcar7/sbml',
#     'https://jjj.bio.vu.nl/rest/models/achcar8/sbml',
#     'https://jjj.bio.vu.nl/rest/models/achcar9/sbml',
#     'https://jjj.bio.vu.nl/rest/models/adlung1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/adlung2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/adlung3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/aguda1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/akman1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/akman2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/albert1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/alexander1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/alexander2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/alsheihk1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/amara1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/anderson1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/arnaout1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/arnold1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/arnold10/sbml',
#     'https://jjj.bio.vu.nl/rest/models/arnold10-2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/arnold11/sbml',
#     'https://jjj.bio.vu.nl/rest/models/arnold2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/arnold3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/arnold4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/arnold5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/arnold6/sbml',
#     'https://jjj.bio.vu.nl/rest/models/arnold7/sbml',
#     'https://jjj.bio.vu.nl/rest/models/arnold8/sbml',
#     'https://jjj.bio.vu.nl/rest/models/arnold9/sbml',
#     'https://jjj.bio.vu.nl/rest/models/assmus/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ataullahkhanov1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/attila/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bachar1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bachmann/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bachmann2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bai1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bajaria1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bakker1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/balagadde1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bali/sbml',
#     'https://jjj.bio.vu.nl/rest/models/band1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/band2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/banks1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bartholome1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/becker1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/becker2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/benary1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/benary2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/benson1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bertram1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke10/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke10/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke10/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke10/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke10/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke10/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke11/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke11/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke11/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke11/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke11/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke11/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke12/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke12/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke12/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke12/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke12/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke12/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke13/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke13/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke13/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke13/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke13/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke13/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke14/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke14/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke14/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke14/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke14/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke14/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke15/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke15/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke15/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke15/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke15/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke15/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke16/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke16/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke16/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke16/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke16/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke16/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke17/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke17/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke17/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke17/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke17/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke17/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke18/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke18/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke18/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke18/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke18/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke18/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke19/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke19/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke19/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke19/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke19/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke19/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke20/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke20/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke20/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke20/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke20/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke20/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke21/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke21/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke21/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke21/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke21/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke21/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke22/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke22/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke22/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke22/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke22/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke22/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke23/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke23/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke23/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke23/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke23/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke23/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke24/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke24/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke24/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke24/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke24/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke24/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke25/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke25/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke25/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke25/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke25/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke25/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke26/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke26/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke26/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke26/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke26/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke26/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke27/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke27/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke27/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke27/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke27/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke27/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke28/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke28/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke28/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke28/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke28/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke28/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke29/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke29/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke29/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke29/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke29/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke29/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke30/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke30/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke30/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke30/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke30/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke30/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke6/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke6/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke6/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke6/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke6/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke6/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke7/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke7/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke7/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke7/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke7/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke7/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke8/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke8/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke8/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke8/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke8/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke8/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke9/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke9/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke9/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke9/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke9/sbml',
#     'https://jjj.bio.vu.nl/rest/models/beuke9/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bhartiya1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bier1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bier2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bindschadler1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/blum1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/borghans1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/borghans2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/borghans3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/borisov1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bornheimer1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bosdriesz1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bosdriesz2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bradshaw/sbml',
#     'https://jjj.bio.vu.nl/rest/models/branch3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/branch5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/brands1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bray1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bray2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bruggeman1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bruggeman2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bucher1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bulik1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bulik2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bulik3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bungay1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bungay2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/bungay3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/butenas1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/cai1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/callaway1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/callaway2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/callaway3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/calzone1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/cao1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/cao2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/cao3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/cao4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/chan1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/chance1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/chance2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/chance3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/chassagnole1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/chassagnole2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/chassagnole3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/chassagnole4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/chen3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ciliberto/sbml',
#     'https://jjj.bio.vu.nl/rest/models/clancy1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/clancy2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/clarke1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/cloutier1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/conant1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/conant2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/conradie/sbml',
#     'https://jjj.bio.vu.nl/rest/models/conradie2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/cronwright1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/curien1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/curien2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/curto1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/dallaman1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/dallaman2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/dallepezze1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/dallepezze2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/dano1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/dano2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/dano3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/davis/sbml',
#     'https://jjj.bio.vu.nl/rest/models/deback1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/decroly1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/deineko1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/delcontezerail1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/demin1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/devos/sbml',
#     'https://jjj.bio.vu.nl/rest/models/dixit1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/dupont1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/dupont2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/dupreez1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/dupreez2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/dupreez3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/dupreez4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/dupreez5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/dupreez6/sbml',
#     'https://jjj.bio.vu.nl/rest/models/dupreez7/sbml',
#     'https://jjj.bio.vu.nl/rest/models/edelstein1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ehrenstein1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ehrenstein2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/eissing/sbml',
#     'https://jjj.bio.vu.nl/rest/models/elowitz1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/essunger1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/essunger2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/essunger3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/essunger4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/fan1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/fan2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/faratian1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/feedbackmoi/sbml',
#     'https://jjj.bio.vu.nl/rest/models/fernandez1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/fernandez2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ferreira1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/figueiredo1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/figueiredo2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/figueiredo3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/figueiredo4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/figueiredo5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/figueiredo6/sbml',
#     'https://jjj.bio.vu.nl/rest/models/fisher1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/fisher2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/francois1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/fraser1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/fraser2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/fribourg1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/fribourg2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/fridlyand1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/friedland1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/fuentes1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/fujita/sbml',
#     'https://jjj.bio.vu.nl/rest/models/fung1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/fuss1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/galazzo1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/gardner1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/geenen/sbml',
#     'https://jjj.bio.vu.nl/rest/models/goldbeter1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/goldbeter2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/goldbeter3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/goldbeter4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/goldbeter5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/goldbeter6/sbml',
#     'https://jjj.bio.vu.nl/rest/models/goldbeter7/sbml',
#     'https://jjj.bio.vu.nl/rest/models/goldbeter8/sbml',
#     'https://jjj.bio.vu.nl/rest/models/gomes/sbml',
#     'https://jjj.bio.vu.nl/rest/models/goodman/sbml',
#     'https://jjj.bio.vu.nl/rest/models/gorlich1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/gould1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/gumel1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/gustavsson1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/gustavsson2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/gustavsson3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/gustavsson4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/gustavsson5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/haanstra/sbml',
#     'https://jjj.bio.vu.nl/rest/models/hald/sbml',
#     'https://jjj.bio.vu.nl/rest/models/hatakeyama1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/haus1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/haus2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/haus3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/haus4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/heinrich/sbml',
#     'https://jjj.bio.vu.nl/rest/models/heldt1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/hernandezvargas1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ho1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/hockin1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/hockin2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/hodgkin/sbml',
#     'https://jjj.bio.vu.nl/rest/models/hoefnagel1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/hoefnagel2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/hoefnagel_mixedacid/sbml',
#     'https://jjj.bio.vu.nl/rest/models/hoffmann1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/hoffmann2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/hofmeyr1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/holzhutter/sbml',
#     'https://jjj.bio.vu.nl/rest/models/hong1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/hornberg1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/huo1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/hynne/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ibrahim1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ibrahim2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ibrahim3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ibrahim4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ihekwaba/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ihekwaba1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/iwami1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/jabbari/sbml',
#     'https://jjj.bio.vu.nl/rest/models/jabbari2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/jamshidi/sbml',
#     'https://jjj.bio.vu.nl/rest/models/jansen1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/jenkinson1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/jiang1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/jones1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/jullesson1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/jullesson2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kallenberger1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kallenberger2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kallenberger3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kallenberger4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kamboj1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/karin1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/karin2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/karin3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/karin4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/karin5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/karin6/sbml',
#     'https://jjj.bio.vu.nl/rest/models/karin7/sbml',
#     'https://jjj.bio.vu.nl/rest/models/keizer1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kerkhovena/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kerkhovenc/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kholodenko1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kholodenko2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kim1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kim2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kim3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kim4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kim5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kintuta/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kintutb/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kintutc/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kintutd/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kirschner1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/klipp1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kofahl1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kolmeisky1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kolodkin1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kolodkin2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kolodkin3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kolodkin4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kolodkin5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kolodkin6/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kolodkin7/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kolodkin8/sbml',
#     'https://jjj.bio.vu.nl/rest/models/komarova1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/komarova2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kongas1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/koo1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/koo2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/koo3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/koo4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/koster/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kouril1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kouril2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kouril3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kouril4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kouril5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kouril6/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kouril7/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kouril8/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kouril9/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kowald1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/krab/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kuhn1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/kummer1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/lambeth/sbml',
#     'https://jjj.bio.vu.nl/rest/models/landi1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/laub/sbml',
#     'https://jjj.bio.vu.nl/rest/models/laub1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/lavrentovich1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/lebeda1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/lebeda2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/leber1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/lee/sbml',
#     'https://jjj.bio.vu.nl/rest/models/lee2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/lee3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/lee4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/legewie1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/legewie2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/leloup1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/leloup2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/leloup3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/leloup4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/leloup5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/leloup6/sbml',
#     'https://jjj.bio.vu.nl/rest/models/leroux/sbml',
#     'https://jjj.bio.vu.nl/rest/models/leroux2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/levchenko1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/levchenko2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/levering1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/levering2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/li1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/li2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/liebal1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/liebal2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/liebal3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/lin1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/lin2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/lin3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/lin3_eq/sbml',
#     'https://jjj.bio.vu.nl/rest/models/lin3moi/sbml',
#     'https://jjj.bio.vu.nl/rest/models/liu1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/liu2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/locke1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/lou1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ma/sbml',
#     'https://jjj.bio.vu.nl/rest/models/machado1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/maeda1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/maher1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/maiwald/sbml',
#     'https://jjj.bio.vu.nl/rest/models/mandlik1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/marhl/sbml',
#     'https://jjj.bio.vu.nl/rest/models/marinhernandez1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/marinhernandez2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/marinhernandez3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/martins/sbml',
#     'https://jjj.bio.vu.nl/rest/models/martins1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/martins2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/marwan1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/mayya/sbml',
#     'https://jjj.bio.vu.nl/rest/models/mayya1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/mcauley1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/mellor1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/messiha1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/messiha2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/messiha3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/miao1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/miao2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/middleton1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/moghadas1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/mol1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/montagne1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/montanez1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/moriya1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/morris1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/mosca1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/mueller1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/mulquiney/sbml',
#     'https://jjj.bio.vu.nl/rest/models/mulquiney1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/mulquiney2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/muraro1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/murray1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/nakakuki1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/nakakuki2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/naresh1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/naresh2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/nazaret1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/neumann1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/neves1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/nguyen/sbml',
#     'https://jjj.bio.vu.nl/rest/models/nielsen/sbml',
#     'https://jjj.bio.vu.nl/rest/models/niger1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/nishio1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/novak/sbml',
#     'https://jjj.bio.vu.nl/rest/models/novak1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/nyabadza1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/nyabadza3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/nyman1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/nyman2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/nyman3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/obeyesekere/sbml',
#     'https://jjj.bio.vu.nl/rest/models/obeyesekere1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/odea1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/okrinya1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/olah/sbml',
#     'https://jjj.bio.vu.nl/rest/models/olivier/sbml',
#     'https://jjj.bio.vu.nl/rest/models/olsen/sbml',
#     'https://jjj.bio.vu.nl/rest/models/orfao1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ortega/sbml',
#     'https://jjj.bio.vu.nl/rest/models/orth1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ouattara1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ouzounoglou1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/oxhamre/sbml',
#     'https://jjj.bio.vu.nl/rest/models/palini1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/pankavich1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/pankavich2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/panteleev1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/panteleev2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/panteleev3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/passos1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/pathak1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/pathak2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/penkler1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/penkler2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/penkler2aa/sbml',
#     'https://jjj.bio.vu.nl/rest/models/perelson1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/perelson2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/perelson3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/pfeiffer1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/piedrafita1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/podder1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/poolman/sbml',
#     'https://jjj.bio.vu.nl/rest/models/praestgaard1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/praestgaard2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/praestgaard3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/pritchard1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/pritchart1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/proctor1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/qi1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/qi2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/queralt/sbml',
#     'https://jjj.bio.vu.nl/rest/models/queralt1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/raia1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/raia2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ralser1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ratushny1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ratushny2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ratushny3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ratushny4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ratushny5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/reed/sbml',
#     'https://jjj.bio.vu.nl/rest/models/rehm1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/revilla1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/revilla2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ribeiro1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/roblitz1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/rohwer1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/rohwer2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/romond1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/rong1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/rong2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/rong3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/rovers1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/roy1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/saavedra/sbml',
#     'https://jjj.bio.vu.nl/rest/models/saeidi1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/santolini1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/sarma1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/sarma2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/sarma3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/sarma4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/sarma5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/sarma6/sbml',
#     'https://jjj.bio.vu.nl/rest/models/sarma7/sbml',
#     'https://jjj.bio.vu.nl/rest/models/sarma8/sbml',
#     'https://jjj.bio.vu.nl/rest/models/sarma9/sbml',
#     'https://jjj.bio.vu.nl/rest/models/schaber/sbml',
#     'https://jjj.bio.vu.nl/rest/models/schaber1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/scheper1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/schilling1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/schliemann1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/schoeberl/sbml',
#     'https://jjj.bio.vu.nl/rest/models/schoeberl1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/sedaghat1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/sen1-2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/sengupta1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/sharp1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/shen1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/shen2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/shen3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/shenorr1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/shu1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/silva/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone0/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone10/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone11/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone12/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone13/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone14/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone15/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone16/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone17/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone18/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone19/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone20/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone21/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone22/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone23/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone6/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone7/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone8/sbml',
#     'https://jjj.bio.vu.nl/rest/models/smallbone9/sbml',
#     'https://jjj.bio.vu.nl/rest/models/snoep/sbml',
#     'https://jjj.bio.vu.nl/rest/models/snoep1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/snoep2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/somogyi1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/somogyi2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/speirs1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/srimani1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/srivastava1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/srivastava2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/stafford1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/strasen1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/strasen10/sbml',
#     'https://jjj.bio.vu.nl/rest/models/strasen11/sbml',
#     'https://jjj.bio.vu.nl/rest/models/strasen2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/strasen3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/strasen4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/strasen5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/strasen6/sbml',
#     'https://jjj.bio.vu.nl/rest/models/strasen7/sbml',
#     'https://jjj.bio.vu.nl/rest/models/strasen8/sbml',
#     'https://jjj.bio.vu.nl/rest/models/strasen9/sbml',
#     'https://jjj.bio.vu.nl/rest/models/supplydemand/sbml',
#     'https://jjj.bio.vu.nl/rest/models/supplydemand2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/tan1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/tang1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/teusink/sbml',
#     'https://jjj.bio.vu.nl/rest/models/teusink2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/thomsen1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/thomsen2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/tiago1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/tiago2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/tiago3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/tripathi1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/twoenzymecompinh1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/twoenzymeparcompinh1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/twoenzymeparcompinh2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/twycross/sbml',
#     'https://jjj.bio.vu.nl/rest/models/tyson10/sbml',
#     'https://jjj.bio.vu.nl/rest/models/tyson11/sbml',
#     'https://jjj.bio.vu.nl/rest/models/tyson12/sbml',
#     'https://jjj.bio.vu.nl/rest/models/tyson13/sbml',
#     'https://jjj.bio.vu.nl/rest/models/tyson14/sbml',
#     'https://jjj.bio.vu.nl/rest/models/tyson2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/tyson3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/tyson4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/tyson5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/tyson6/sbml',
#     'https://jjj.bio.vu.nl/rest/models/tyson7/sbml',
#     'https://jjj.bio.vu.nl/rest/models/tyson8/sbml',
#     'https://jjj.bio.vu.nl/rest/models/tyson9/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ueda1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/ung1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/uys/sbml',
#     'https://jjj.bio.vu.nl/rest/models/valero/sbml',
#     'https://jjj.bio.vu.nl/rest/models/vaneunen1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/vaneunen2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/vaneunen3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/vaneunen4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/vaneunen5/sbml',
#     'https://jjj.bio.vu.nl/rest/models/vaneunen6/sbml',
#     'https://jjj.bio.vu.nl/rest/models/vaneunen7/sbml',
#     'https://jjj.bio.vu.nl/rest/models/vanheerden1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/vanheerden2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/vanniekerk1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/veening1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/venturelli1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/venturelli2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/venturelli3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/venturelli4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/vernoux1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/vernoux2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/vilar1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/vilar2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/voit1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/wahl1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/wang/sbml',
#     'https://jjj.bio.vu.nl/rest/models/wang1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/wang2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/wang3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/wegner1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/weimann1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/westerhoff1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/westermark/sbml',
#     'https://jjj.bio.vu.nl/rest/models/whillier1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/whillier2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/whillier3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/whillier4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/wilhelm1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/wodarz1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/wodarz3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/wolf/sbml',
#     'https://jjj.bio.vu.nl/rest/models/wolf1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/wolf2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/wortel1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/wortel2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/wortel3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/wortel4/sbml',
#     'https://jjj.bio.vu.nl/rest/models/wu1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/xie1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/xu/sbml',
#     'https://jjj.bio.vu.nl/rest/models/yamada1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/yamada2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/yang/sbml',
#     'https://jjj.bio.vu.nl/rest/models/yao1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/yildirim1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/yugi1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/yugi2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/zatorskyc/sbml',
#     'https://jjj.bio.vu.nl/rest/models/zatorskyd/sbml',
#     'https://jjj.bio.vu.nl/rest/models/zatorskye/sbml',
#     'https://jjj.bio.vu.nl/rest/models/zeilinger1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/zeilinger2/sbml',
#     'https://jjj.bio.vu.nl/rest/models/zeilinger3/sbml',
#     'https://jjj.bio.vu.nl/rest/models/zhao1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/zhu1/sbml',
#     'https://jjj.bio.vu.nl/rest/models/zi1/sbml',
# ]

sbml_files = [
    'https://jjj.bio.vu.nl/rest/models/abudukelimu1/sbml',
    'https://jjj.bio.vu.nl/rest/models/achcar1/sbml',
    'https://jjj.bio.vu.nl/rest/models/achcar10/sbml',
    'https://jjj.bio.vu.nl/rest/models/achcar11/sbml',
    'https://jjj.bio.vu.nl/rest/models/achcar12/sbml',
    'https://jjj.bio.vu.nl/rest/models/achcar13/sbml',
    'https://jjj.bio.vu.nl/rest/models/achcar14/sbml',
    'https://jjj.bio.vu.nl/rest/models/achcar2/sbml',
    'https://jjj.bio.vu.nl/rest/models/achcar3/sbml',
    'https://jjj.bio.vu.nl/rest/models/achcar4/sbml',
    'https://jjj.bio.vu.nl/rest/models/achcar5/sbml',
    'https://jjj.bio.vu.nl/rest/models/achcar6/sbml',
    'https://jjj.bio.vu.nl/rest/models/achcar7/sbml',
    'https://jjj.bio.vu.nl/rest/models/achcar8/sbml',
    'https://jjj.bio.vu.nl/rest/models/achcar9/sbml',
    'https://jjj.bio.vu.nl/rest/models/adlung1/sbml',
    'https://jjj.bio.vu.nl/rest/models/adlung2/sbml',
    'https://jjj.bio.vu.nl/rest/models/adlung3/sbml',
    'https://jjj.bio.vu.nl/rest/models/aguda1/sbml',
    'https://jjj.bio.vu.nl/rest/models/akman1/sbml',
    'https://jjj.bio.vu.nl/rest/models/akman2/sbml',
    'https://jjj.bio.vu.nl/rest/models/albert1/sbml',
    'https://jjj.bio.vu.nl/rest/models/alexander1/sbml',
    'https://jjj.bio.vu.nl/rest/models/alexander2/sbml',
    'https://jjj.bio.vu.nl/rest/models/alsheihk1/sbml',
    'https://jjj.bio.vu.nl/rest/models/amara1/sbml',
    'https://jjj.bio.vu.nl/rest/models/anderson1/sbml',
    'https://jjj.bio.vu.nl/rest/models/arnaout1/sbml',
    'https://jjj.bio.vu.nl/rest/models/arnold10/sbml',
    'https://jjj.bio.vu.nl/rest/models/arnold10-2/sbml',
    'https://jjj.bio.vu.nl/rest/models/arnold11/sbml',
    'https://jjj.bio.vu.nl/rest/models/arnold4/sbml',
    'https://jjj.bio.vu.nl/rest/models/arnold6/sbml',
    'https://jjj.bio.vu.nl/rest/models/arnold7/sbml',
    'https://jjj.bio.vu.nl/rest/models/arnold8/sbml',
    'https://jjj.bio.vu.nl/rest/models/arnold9/sbml',
    'https://jjj.bio.vu.nl/rest/models/assmus/sbml',
    'https://jjj.bio.vu.nl/rest/models/ataullahkhanov1/sbml',
    'https://jjj.bio.vu.nl/rest/models/attila/sbml',
    'https://jjj.bio.vu.nl/rest/models/bachar1/sbml',
    'https://jjj.bio.vu.nl/rest/models/bachmann/sbml',
    'https://jjj.bio.vu.nl/rest/models/bachmann2/sbml',
    'https://jjj.bio.vu.nl/rest/models/bai1/sbml',
    'https://jjj.bio.vu.nl/rest/models/bajaria1/sbml',
    'https://jjj.bio.vu.nl/rest/models/bakker1/sbml',
    'https://jjj.bio.vu.nl/rest/models/balagadde1/sbml',
    'https://jjj.bio.vu.nl/rest/models/bali/sbml',
    'https://jjj.bio.vu.nl/rest/models/band1/sbml',
    'https://jjj.bio.vu.nl/rest/models/band2/sbml',
    'https://jjj.bio.vu.nl/rest/models/banks1/sbml',
    'https://jjj.bio.vu.nl/rest/models/bartholome1/sbml',
    'https://jjj.bio.vu.nl/rest/models/becker1/sbml',
    'https://jjj.bio.vu.nl/rest/models/becker2/sbml',
    'https://jjj.bio.vu.nl/rest/models/benary1/sbml',
    'https://jjj.bio.vu.nl/rest/models/benary2/sbml',
    'https://jjj.bio.vu.nl/rest/models/benson1/sbml',
    'https://jjj.bio.vu.nl/rest/models/bertram1/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke1/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke10/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke11/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke12/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke13/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke14/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke15/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke16/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke17/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke18/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke19/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke2/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke20/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke21/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke22/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke23/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke24/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke25/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke26/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke27/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke28/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke29/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke3/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke30/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke4/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke5/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke6/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke7/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke8/sbml',
    'https://jjj.bio.vu.nl/rest/models/beuke9/sbml',
    'https://jjj.bio.vu.nl/rest/models/bhartiya1/sbml',
    'https://jjj.bio.vu.nl/rest/models/bier1/sbml',
    'https://jjj.bio.vu.nl/rest/models/bier2/sbml',
    'https://jjj.bio.vu.nl/rest/models/bindschadler1/sbml',
    'https://jjj.bio.vu.nl/rest/models/blum1/sbml',
    'https://jjj.bio.vu.nl/rest/models/borghans1/sbml',
    'https://jjj.bio.vu.nl/rest/models/borghans2/sbml',
    'https://jjj.bio.vu.nl/rest/models/borghans3/sbml',
    'https://jjj.bio.vu.nl/rest/models/borisov1/sbml',
    'https://jjj.bio.vu.nl/rest/models/bornheimer1/sbml',
    'https://jjj.bio.vu.nl/rest/models/bosdriesz1/sbml',
    'https://jjj.bio.vu.nl/rest/models/bosdriesz2/sbml',
    'https://jjj.bio.vu.nl/rest/models/bradshaw/sbml',
    'https://jjj.bio.vu.nl/rest/models/branch3/sbml',
    'https://jjj.bio.vu.nl/rest/models/branch5/sbml',
    'https://jjj.bio.vu.nl/rest/models/brands1/sbml',
    'https://jjj.bio.vu.nl/rest/models/bray1/sbml',
    'https://jjj.bio.vu.nl/rest/models/bray2/sbml',
    'https://jjj.bio.vu.nl/rest/models/bruggeman1/sbml',
    'https://jjj.bio.vu.nl/rest/models/bruggeman2/sbml',
    'https://jjj.bio.vu.nl/rest/models/bucher1/sbml',
    'https://jjj.bio.vu.nl/rest/models/bulik1/sbml',
    'https://jjj.bio.vu.nl/rest/models/bulik2/sbml',
    'https://jjj.bio.vu.nl/rest/models/bulik3/sbml',
    'https://jjj.bio.vu.nl/rest/models/bungay1/sbml',
    'https://jjj.bio.vu.nl/rest/models/bungay2/sbml',
    'https://jjj.bio.vu.nl/rest/models/bungay3/sbml',
    'https://jjj.bio.vu.nl/rest/models/butenas1/sbml',
    'https://jjj.bio.vu.nl/rest/models/cai1/sbml',
    'https://jjj.bio.vu.nl/rest/models/callaway1/sbml',
    'https://jjj.bio.vu.nl/rest/models/callaway2/sbml',
    'https://jjj.bio.vu.nl/rest/models/callaway3/sbml',
    'https://jjj.bio.vu.nl/rest/models/calzone1/sbml',
    'https://jjj.bio.vu.nl/rest/models/cao1/sbml',
    'https://jjj.bio.vu.nl/rest/models/cao2/sbml',
    'https://jjj.bio.vu.nl/rest/models/cao3/sbml',
    'https://jjj.bio.vu.nl/rest/models/cao4/sbml',
    'https://jjj.bio.vu.nl/rest/models/chan1/sbml',
    'https://jjj.bio.vu.nl/rest/models/chance1/sbml',
    'https://jjj.bio.vu.nl/rest/models/chance2/sbml',
    'https://jjj.bio.vu.nl/rest/models/chance3/sbml',
    'https://jjj.bio.vu.nl/rest/models/chassagnole1/sbml',
    'https://jjj.bio.vu.nl/rest/models/chassagnole2/sbml',
    'https://jjj.bio.vu.nl/rest/models/chassagnole3/sbml',
    'https://jjj.bio.vu.nl/rest/models/chassagnole4/sbml',
    'https://jjj.bio.vu.nl/rest/models/chen3/sbml',
    'https://jjj.bio.vu.nl/rest/models/ciliberto/sbml',
    'https://jjj.bio.vu.nl/rest/models/clancy1/sbml',
    'https://jjj.bio.vu.nl/rest/models/clancy2/sbml',
    'https://jjj.bio.vu.nl/rest/models/clarke1/sbml',
    'https://jjj.bio.vu.nl/rest/models/cloutier1/sbml',
    'https://jjj.bio.vu.nl/rest/models/conant1/sbml',
    'https://jjj.bio.vu.nl/rest/models/conant2/sbml',
    'https://jjj.bio.vu.nl/rest/models/conradie/sbml',
    'https://jjj.bio.vu.nl/rest/models/conradie2/sbml',
    'https://jjj.bio.vu.nl/rest/models/cronwright1/sbml',
    'https://jjj.bio.vu.nl/rest/models/curien1/sbml',
    'https://jjj.bio.vu.nl/rest/models/curien2/sbml',
    'https://jjj.bio.vu.nl/rest/models/curto1/sbml',
    'https://jjj.bio.vu.nl/rest/models/dallaman1/sbml',
    'https://jjj.bio.vu.nl/rest/models/dallaman2/sbml',
    'https://jjj.bio.vu.nl/rest/models/dallepezze1/sbml',
    'https://jjj.bio.vu.nl/rest/models/dallepezze2/sbml',
    'https://jjj.bio.vu.nl/rest/models/dano1/sbml',
    'https://jjj.bio.vu.nl/rest/models/dano2/sbml',
    'https://jjj.bio.vu.nl/rest/models/dano3/sbml',
    'https://jjj.bio.vu.nl/rest/models/davis/sbml',
    'https://jjj.bio.vu.nl/rest/models/deback1/sbml',
    'https://jjj.bio.vu.nl/rest/models/decroly1/sbml',
    'https://jjj.bio.vu.nl/rest/models/deineko1/sbml',
    'https://jjj.bio.vu.nl/rest/models/delcontezerail1/sbml',
    'https://jjj.bio.vu.nl/rest/models/demin1/sbml',
    'https://jjj.bio.vu.nl/rest/models/devos/sbml',
    'https://jjj.bio.vu.nl/rest/models/dixit1/sbml',
    'https://jjj.bio.vu.nl/rest/models/dupont1/sbml',
    'https://jjj.bio.vu.nl/rest/models/dupont2/sbml',
    'https://jjj.bio.vu.nl/rest/models/dupreez1/sbml',
    'https://jjj.bio.vu.nl/rest/models/dupreez2/sbml',
    'https://jjj.bio.vu.nl/rest/models/dupreez3/sbml',
    'https://jjj.bio.vu.nl/rest/models/dupreez4/sbml',
    'https://jjj.bio.vu.nl/rest/models/dupreez5/sbml',
    'https://jjj.bio.vu.nl/rest/models/dupreez6/sbml',
    'https://jjj.bio.vu.nl/rest/models/dupreez7/sbml',
    'https://jjj.bio.vu.nl/rest/models/edelstein1/sbml',
    'https://jjj.bio.vu.nl/rest/models/eissing/sbml',
    'https://jjj.bio.vu.nl/rest/models/elowitz1/sbml',
    'https://jjj.bio.vu.nl/rest/models/essunger1/sbml',
    'https://jjj.bio.vu.nl/rest/models/essunger2/sbml',
    'https://jjj.bio.vu.nl/rest/models/essunger3/sbml',
    'https://jjj.bio.vu.nl/rest/models/essunger4/sbml',
    'https://jjj.bio.vu.nl/rest/models/fan1/sbml',
    'https://jjj.bio.vu.nl/rest/models/fan2/sbml',
    'https://jjj.bio.vu.nl/rest/models/feedbackmoi/sbml',
    'https://jjj.bio.vu.nl/rest/models/fernandez1/sbml',
    'https://jjj.bio.vu.nl/rest/models/fernandez2/sbml',
    'https://jjj.bio.vu.nl/rest/models/ferreira1/sbml',
    'https://jjj.bio.vu.nl/rest/models/figueiredo1/sbml',
    'https://jjj.bio.vu.nl/rest/models/figueiredo2/sbml',
    'https://jjj.bio.vu.nl/rest/models/figueiredo3/sbml',
    'https://jjj.bio.vu.nl/rest/models/figueiredo4/sbml',
    'https://jjj.bio.vu.nl/rest/models/figueiredo5/sbml',
    'https://jjj.bio.vu.nl/rest/models/figueiredo6/sbml',
    'https://jjj.bio.vu.nl/rest/models/fisher1/sbml',
    'https://jjj.bio.vu.nl/rest/models/fisher2/sbml',
    'https://jjj.bio.vu.nl/rest/models/francois1/sbml',
    'https://jjj.bio.vu.nl/rest/models/fraser1/sbml',
    'https://jjj.bio.vu.nl/rest/models/fraser2/sbml',
    'https://jjj.bio.vu.nl/rest/models/fribourg1/sbml',
    'https://jjj.bio.vu.nl/rest/models/fribourg2/sbml',
    'https://jjj.bio.vu.nl/rest/models/fridlyand1/sbml',
    'https://jjj.bio.vu.nl/rest/models/friedland1/sbml',
    'https://jjj.bio.vu.nl/rest/models/fuentes1/sbml',
    'https://jjj.bio.vu.nl/rest/models/fujita/sbml',
    'https://jjj.bio.vu.nl/rest/models/fung1/sbml',
    'https://jjj.bio.vu.nl/rest/models/fuss1/sbml',
    'https://jjj.bio.vu.nl/rest/models/galazzo1/sbml',
    'https://jjj.bio.vu.nl/rest/models/gardner1/sbml',
    'https://jjj.bio.vu.nl/rest/models/geenen/sbml',
    'https://jjj.bio.vu.nl/rest/models/goldbeter1/sbml',
    'https://jjj.bio.vu.nl/rest/models/goldbeter2/sbml',
    'https://jjj.bio.vu.nl/rest/models/goldbeter3/sbml',
    'https://jjj.bio.vu.nl/rest/models/goldbeter4/sbml',
    'https://jjj.bio.vu.nl/rest/models/goldbeter5/sbml',
    'https://jjj.bio.vu.nl/rest/models/goldbeter6/sbml',
    'https://jjj.bio.vu.nl/rest/models/goldbeter7/sbml',
    'https://jjj.bio.vu.nl/rest/models/goldbeter8/sbml',
    'https://jjj.bio.vu.nl/rest/models/gomes/sbml',
    'https://jjj.bio.vu.nl/rest/models/goodman/sbml',
    'https://jjj.bio.vu.nl/rest/models/gorlich1/sbml',
    'https://jjj.bio.vu.nl/rest/models/gould1/sbml',
    'https://jjj.bio.vu.nl/rest/models/gumel1/sbml',
    'https://jjj.bio.vu.nl/rest/models/gustavsson1/sbml',
    'https://jjj.bio.vu.nl/rest/models/gustavsson2/sbml',
    'https://jjj.bio.vu.nl/rest/models/gustavsson3/sbml',
    'https://jjj.bio.vu.nl/rest/models/gustavsson4/sbml',
    'https://jjj.bio.vu.nl/rest/models/gustavsson5/sbml',
    'https://jjj.bio.vu.nl/rest/models/haanstra/sbml',
    'https://jjj.bio.vu.nl/rest/models/hald/sbml',
    'https://jjj.bio.vu.nl/rest/models/hatakeyama1/sbml',
    'https://jjj.bio.vu.nl/rest/models/haus1/sbml',
    'https://jjj.bio.vu.nl/rest/models/haus2/sbml',
    'https://jjj.bio.vu.nl/rest/models/haus3/sbml',
    'https://jjj.bio.vu.nl/rest/models/haus4/sbml',
    'https://jjj.bio.vu.nl/rest/models/heinrich/sbml',
    'https://jjj.bio.vu.nl/rest/models/heldt1/sbml',
    'https://jjj.bio.vu.nl/rest/models/hernandezvargas1/sbml',
    'https://jjj.bio.vu.nl/rest/models/ho1/sbml',
    'https://jjj.bio.vu.nl/rest/models/hockin1/sbml',
    'https://jjj.bio.vu.nl/rest/models/hockin2/sbml',
    'https://jjj.bio.vu.nl/rest/models/hodgkin/sbml',
    'https://jjj.bio.vu.nl/rest/models/hoefnagel1/sbml',
    'https://jjj.bio.vu.nl/rest/models/hoefnagel2/sbml',
    'https://jjj.bio.vu.nl/rest/models/hoefnagel_mixedacid/sbml',
    'https://jjj.bio.vu.nl/rest/models/hoffmann1/sbml',
    'https://jjj.bio.vu.nl/rest/models/hoffmann2/sbml',
    'https://jjj.bio.vu.nl/rest/models/hofmeyr1/sbml',
    'https://jjj.bio.vu.nl/rest/models/holzhutter/sbml',
    'https://jjj.bio.vu.nl/rest/models/hong1/sbml',
    'https://jjj.bio.vu.nl/rest/models/hornberg1/sbml',
    'https://jjj.bio.vu.nl/rest/models/huo1/sbml',
    'https://jjj.bio.vu.nl/rest/models/hynne/sbml',
    'https://jjj.bio.vu.nl/rest/models/ibrahim1/sbml',
    'https://jjj.bio.vu.nl/rest/models/ibrahim2/sbml',
    'https://jjj.bio.vu.nl/rest/models/ibrahim3/sbml',
    'https://jjj.bio.vu.nl/rest/models/ibrahim4/sbml',
    'https://jjj.bio.vu.nl/rest/models/ihekwaba/sbml',
    'https://jjj.bio.vu.nl/rest/models/ihekwaba1/sbml',
    'https://jjj.bio.vu.nl/rest/models/iwami1/sbml',
    'https://jjj.bio.vu.nl/rest/models/jabbari/sbml',
    'https://jjj.bio.vu.nl/rest/models/jabbari2/sbml',
    'https://jjj.bio.vu.nl/rest/models/jamshidi/sbml',
    'https://jjj.bio.vu.nl/rest/models/jansen1/sbml',
    'https://jjj.bio.vu.nl/rest/models/jenkinson1/sbml',
    'https://jjj.bio.vu.nl/rest/models/jiang1/sbml',
    'https://jjj.bio.vu.nl/rest/models/jones1/sbml',
    'https://jjj.bio.vu.nl/rest/models/jullesson1/sbml',
    'https://jjj.bio.vu.nl/rest/models/jullesson2/sbml',
    'https://jjj.bio.vu.nl/rest/models/kallenberger1/sbml',
    'https://jjj.bio.vu.nl/rest/models/kallenberger2/sbml',
    'https://jjj.bio.vu.nl/rest/models/kallenberger3/sbml',
    'https://jjj.bio.vu.nl/rest/models/kallenberger4/sbml',
    'https://jjj.bio.vu.nl/rest/models/kamboj1/sbml',
    'https://jjj.bio.vu.nl/rest/models/karin1/sbml',
    'https://jjj.bio.vu.nl/rest/models/karin2/sbml',
    'https://jjj.bio.vu.nl/rest/models/karin3/sbml',
    'https://jjj.bio.vu.nl/rest/models/karin4/sbml',
    'https://jjj.bio.vu.nl/rest/models/karin5/sbml',
    'https://jjj.bio.vu.nl/rest/models/karin6/sbml',
    'https://jjj.bio.vu.nl/rest/models/karin7/sbml',
    'https://jjj.bio.vu.nl/rest/models/keizer1/sbml',
    'https://jjj.bio.vu.nl/rest/models/kerkhovena/sbml',
    'https://jjj.bio.vu.nl/rest/models/kerkhovenc/sbml',
    'https://jjj.bio.vu.nl/rest/models/kholodenko1/sbml',
    'https://jjj.bio.vu.nl/rest/models/kholodenko2/sbml',
    'https://jjj.bio.vu.nl/rest/models/kim1/sbml',
    'https://jjj.bio.vu.nl/rest/models/kim2/sbml',
    'https://jjj.bio.vu.nl/rest/models/kim3/sbml',
    'https://jjj.bio.vu.nl/rest/models/kim4/sbml',
    'https://jjj.bio.vu.nl/rest/models/kim5/sbml',
    'https://jjj.bio.vu.nl/rest/models/kintuta/sbml',
    'https://jjj.bio.vu.nl/rest/models/kintutb/sbml',
    'https://jjj.bio.vu.nl/rest/models/kintutc/sbml',
    'https://jjj.bio.vu.nl/rest/models/kintutd/sbml',
    'https://jjj.bio.vu.nl/rest/models/kirschner1/sbml',
    'https://jjj.bio.vu.nl/rest/models/klipp1/sbml',
    'https://jjj.bio.vu.nl/rest/models/kofahl1/sbml',
    'https://jjj.bio.vu.nl/rest/models/kolmeisky1/sbml',
    'https://jjj.bio.vu.nl/rest/models/kolodkin1/sbml',
    'https://jjj.bio.vu.nl/rest/models/kolodkin2/sbml',
    'https://jjj.bio.vu.nl/rest/models/kolodkin3/sbml',
    'https://jjj.bio.vu.nl/rest/models/kolodkin4/sbml',
    'https://jjj.bio.vu.nl/rest/models/kolodkin5/sbml',
    'https://jjj.bio.vu.nl/rest/models/kolodkin6/sbml',
    'https://jjj.bio.vu.nl/rest/models/kolodkin7/sbml',
    'https://jjj.bio.vu.nl/rest/models/kolodkin8/sbml',
    'https://jjj.bio.vu.nl/rest/models/komarova1/sbml',
    'https://jjj.bio.vu.nl/rest/models/komarova2/sbml',
    'https://jjj.bio.vu.nl/rest/models/kongas1/sbml',
    'https://jjj.bio.vu.nl/rest/models/koo1/sbml',
    'https://jjj.bio.vu.nl/rest/models/koo2/sbml',
    'https://jjj.bio.vu.nl/rest/models/koo3/sbml',
    'https://jjj.bio.vu.nl/rest/models/koo4/sbml',
    'https://jjj.bio.vu.nl/rest/models/koster/sbml',
    'https://jjj.bio.vu.nl/rest/models/kouril1/sbml',
    'https://jjj.bio.vu.nl/rest/models/kouril2/sbml',
    'https://jjj.bio.vu.nl/rest/models/kouril3/sbml',
    'https://jjj.bio.vu.nl/rest/models/kouril4/sbml',
    'https://jjj.bio.vu.nl/rest/models/kouril5/sbml',
    'https://jjj.bio.vu.nl/rest/models/kouril6/sbml',
    'https://jjj.bio.vu.nl/rest/models/kouril7/sbml',
    'https://jjj.bio.vu.nl/rest/models/kouril8/sbml',
    'https://jjj.bio.vu.nl/rest/models/kouril9/sbml',
    'https://jjj.bio.vu.nl/rest/models/kowald1/sbml',
    'https://jjj.bio.vu.nl/rest/models/krab/sbml',
    'https://jjj.bio.vu.nl/rest/models/kuhn1/sbml',
    'https://jjj.bio.vu.nl/rest/models/kummer1/sbml',
    'https://jjj.bio.vu.nl/rest/models/lambeth/sbml',
    'https://jjj.bio.vu.nl/rest/models/landi1/sbml',
    'https://jjj.bio.vu.nl/rest/models/laub/sbml',
    'https://jjj.bio.vu.nl/rest/models/laub1/sbml',
    'https://jjj.bio.vu.nl/rest/models/lavrentovich1/sbml',
    'https://jjj.bio.vu.nl/rest/models/lebeda1/sbml',
    'https://jjj.bio.vu.nl/rest/models/lebeda2/sbml',
    'https://jjj.bio.vu.nl/rest/models/leber1/sbml',
    'https://jjj.bio.vu.nl/rest/models/lee/sbml',
    'https://jjj.bio.vu.nl/rest/models/lee2/sbml',
    'https://jjj.bio.vu.nl/rest/models/lee3/sbml',
    'https://jjj.bio.vu.nl/rest/models/lee4/sbml',
    'https://jjj.bio.vu.nl/rest/models/legewie1/sbml',
    'https://jjj.bio.vu.nl/rest/models/legewie2/sbml',
    'https://jjj.bio.vu.nl/rest/models/leloup1/sbml',
    'https://jjj.bio.vu.nl/rest/models/leloup2/sbml',
    'https://jjj.bio.vu.nl/rest/models/leloup3/sbml',
    'https://jjj.bio.vu.nl/rest/models/leloup4/sbml',
    'https://jjj.bio.vu.nl/rest/models/leloup5/sbml',
    'https://jjj.bio.vu.nl/rest/models/leloup6/sbml',
    'https://jjj.bio.vu.nl/rest/models/leroux/sbml',
    'https://jjj.bio.vu.nl/rest/models/leroux2/sbml',
    'https://jjj.bio.vu.nl/rest/models/levchenko1/sbml',
    'https://jjj.bio.vu.nl/rest/models/levchenko2/sbml',
    'https://jjj.bio.vu.nl/rest/models/levering1/sbml',
    'https://jjj.bio.vu.nl/rest/models/levering2/sbml',
    'https://jjj.bio.vu.nl/rest/models/li1/sbml',
    'https://jjj.bio.vu.nl/rest/models/li2/sbml',
    'https://jjj.bio.vu.nl/rest/models/liebal1/sbml',
    'https://jjj.bio.vu.nl/rest/models/liebal2/sbml',
    'https://jjj.bio.vu.nl/rest/models/liebal3/sbml',
    'https://jjj.bio.vu.nl/rest/models/lin1/sbml',
    'https://jjj.bio.vu.nl/rest/models/lin2/sbml',
    'https://jjj.bio.vu.nl/rest/models/lin3/sbml',
    'https://jjj.bio.vu.nl/rest/models/lin3_eq/sbml',
    'https://jjj.bio.vu.nl/rest/models/lin3moi/sbml',
    'https://jjj.bio.vu.nl/rest/models/liu1/sbml',
    'https://jjj.bio.vu.nl/rest/models/liu2/sbml',
    'https://jjj.bio.vu.nl/rest/models/locke1/sbml',
    'https://jjj.bio.vu.nl/rest/models/lou1/sbml',
    'https://jjj.bio.vu.nl/rest/models/ma/sbml',
    'https://jjj.bio.vu.nl/rest/models/machado1/sbml',
    'https://jjj.bio.vu.nl/rest/models/maeda1/sbml',
    'https://jjj.bio.vu.nl/rest/models/maher1/sbml',
    'https://jjj.bio.vu.nl/rest/models/maiwald/sbml',
    'https://jjj.bio.vu.nl/rest/models/mandlik1/sbml',
    'https://jjj.bio.vu.nl/rest/models/marhl/sbml',
    'https://jjj.bio.vu.nl/rest/models/marinhernandez1/sbml',
    'https://jjj.bio.vu.nl/rest/models/marinhernandez2/sbml',
    'https://jjj.bio.vu.nl/rest/models/marinhernandez3/sbml',
    'https://jjj.bio.vu.nl/rest/models/martins/sbml',
    'https://jjj.bio.vu.nl/rest/models/martins1/sbml',
    'https://jjj.bio.vu.nl/rest/models/martins2/sbml',
    'https://jjj.bio.vu.nl/rest/models/marwan1/sbml',
    'https://jjj.bio.vu.nl/rest/models/mayya/sbml',
    'https://jjj.bio.vu.nl/rest/models/mayya1/sbml',
    'https://jjj.bio.vu.nl/rest/models/mcauley1/sbml',
    'https://jjj.bio.vu.nl/rest/models/mellor1/sbml',
    'https://jjj.bio.vu.nl/rest/models/messiha1/sbml',
    'https://jjj.bio.vu.nl/rest/models/messiha2/sbml',
    'https://jjj.bio.vu.nl/rest/models/messiha3/sbml',
    'https://jjj.bio.vu.nl/rest/models/miao1/sbml',
    'https://jjj.bio.vu.nl/rest/models/miao2/sbml',
    'https://jjj.bio.vu.nl/rest/models/middleton1/sbml',
    'https://jjj.bio.vu.nl/rest/models/moghadas1/sbml',
    'https://jjj.bio.vu.nl/rest/models/mol1/sbml',
    'https://jjj.bio.vu.nl/rest/models/montagne1/sbml',
    'https://jjj.bio.vu.nl/rest/models/montanez1/sbml',
    'https://jjj.bio.vu.nl/rest/models/moriya1/sbml',
    'https://jjj.bio.vu.nl/rest/models/morris1/sbml',
    'https://jjj.bio.vu.nl/rest/models/mosca1/sbml',
    'https://jjj.bio.vu.nl/rest/models/mueller1/sbml',
    'https://jjj.bio.vu.nl/rest/models/mulquiney/sbml',
    'https://jjj.bio.vu.nl/rest/models/muraro1/sbml',
    'https://jjj.bio.vu.nl/rest/models/murray1/sbml',
    'https://jjj.bio.vu.nl/rest/models/nakakuki1/sbml',
    'https://jjj.bio.vu.nl/rest/models/nakakuki2/sbml',
    'https://jjj.bio.vu.nl/rest/models/naresh1/sbml',
    'https://jjj.bio.vu.nl/rest/models/naresh2/sbml',
    'https://jjj.bio.vu.nl/rest/models/nazaret1/sbml',
    'https://jjj.bio.vu.nl/rest/models/neumann1/sbml',
    'https://jjj.bio.vu.nl/rest/models/neves1/sbml',
    'https://jjj.bio.vu.nl/rest/models/nguyen/sbml',
    'https://jjj.bio.vu.nl/rest/models/nielsen/sbml',
    'https://jjj.bio.vu.nl/rest/models/niger1/sbml',
    'https://jjj.bio.vu.nl/rest/models/nishio1/sbml',
    'https://jjj.bio.vu.nl/rest/models/novak/sbml',
    'https://jjj.bio.vu.nl/rest/models/novak1/sbml',
    'https://jjj.bio.vu.nl/rest/models/nyabadza1/sbml',
    'https://jjj.bio.vu.nl/rest/models/nyabadza3/sbml',
    'https://jjj.bio.vu.nl/rest/models/nyman1/sbml',
    'https://jjj.bio.vu.nl/rest/models/nyman2/sbml',
    'https://jjj.bio.vu.nl/rest/models/nyman3/sbml',
    'https://jjj.bio.vu.nl/rest/models/obeyesekere/sbml',
    'https://jjj.bio.vu.nl/rest/models/obeyesekere1/sbml',
    'https://jjj.bio.vu.nl/rest/models/odea1/sbml',
    'https://jjj.bio.vu.nl/rest/models/okrinya1/sbml',
    'https://jjj.bio.vu.nl/rest/models/olah/sbml',
    'https://jjj.bio.vu.nl/rest/models/olivier/sbml',
    'https://jjj.bio.vu.nl/rest/models/olsen/sbml',
    'https://jjj.bio.vu.nl/rest/models/orfao1/sbml',
    'https://jjj.bio.vu.nl/rest/models/ortega/sbml',
    'https://jjj.bio.vu.nl/rest/models/orth1/sbml',
    'https://jjj.bio.vu.nl/rest/models/ouattara1/sbml',
    'https://jjj.bio.vu.nl/rest/models/ouzounoglou1/sbml',
    'https://jjj.bio.vu.nl/rest/models/oxhamre/sbml',
    'https://jjj.bio.vu.nl/rest/models/palini1/sbml',
    'https://jjj.bio.vu.nl/rest/models/pankavich1/sbml',
    'https://jjj.bio.vu.nl/rest/models/pankavich2/sbml',
    'https://jjj.bio.vu.nl/rest/models/panteleev1/sbml',
    'https://jjj.bio.vu.nl/rest/models/panteleev2/sbml',
    'https://jjj.bio.vu.nl/rest/models/panteleev3/sbml',
    'https://jjj.bio.vu.nl/rest/models/passos1/sbml',
    'https://jjj.bio.vu.nl/rest/models/pathak1/sbml',
    'https://jjj.bio.vu.nl/rest/models/pathak2/sbml',
    'https://jjj.bio.vu.nl/rest/models/penkler2aa/sbml',
    'https://jjj.bio.vu.nl/rest/models/perelson1/sbml',
    'https://jjj.bio.vu.nl/rest/models/perelson2/sbml',
    'https://jjj.bio.vu.nl/rest/models/perelson3/sbml',
    'https://jjj.bio.vu.nl/rest/models/pfeiffer1/sbml',
    'https://jjj.bio.vu.nl/rest/models/piedrafita1/sbml',
    'https://jjj.bio.vu.nl/rest/models/podder1/sbml',
    'https://jjj.bio.vu.nl/rest/models/poolman/sbml',
    'https://jjj.bio.vu.nl/rest/models/praestgaard1/sbml',
    'https://jjj.bio.vu.nl/rest/models/praestgaard2/sbml',
    'https://jjj.bio.vu.nl/rest/models/praestgaard3/sbml',
    'https://jjj.bio.vu.nl/rest/models/pritchard1/sbml',
    'https://jjj.bio.vu.nl/rest/models/pritchart1/sbml',
    'https://jjj.bio.vu.nl/rest/models/proctor1/sbml',
    'https://jjj.bio.vu.nl/rest/models/qi1/sbml',
    'https://jjj.bio.vu.nl/rest/models/qi2/sbml',
    'https://jjj.bio.vu.nl/rest/models/queralt/sbml',
    'https://jjj.bio.vu.nl/rest/models/queralt1/sbml',
    'https://jjj.bio.vu.nl/rest/models/raia1/sbml',
    'https://jjj.bio.vu.nl/rest/models/raia2/sbml',
    'https://jjj.bio.vu.nl/rest/models/ralser1/sbml',
    'https://jjj.bio.vu.nl/rest/models/ratushny1/sbml',
    'https://jjj.bio.vu.nl/rest/models/ratushny2/sbml',
    'https://jjj.bio.vu.nl/rest/models/ratushny3/sbml',
    'https://jjj.bio.vu.nl/rest/models/ratushny4/sbml',
    'https://jjj.bio.vu.nl/rest/models/ratushny5/sbml',
    'https://jjj.bio.vu.nl/rest/models/reed/sbml',
    'https://jjj.bio.vu.nl/rest/models/rehm1/sbml',
    'https://jjj.bio.vu.nl/rest/models/revilla1/sbml',
    'https://jjj.bio.vu.nl/rest/models/revilla2/sbml',
    'https://jjj.bio.vu.nl/rest/models/ribeiro1/sbml',
    'https://jjj.bio.vu.nl/rest/models/roblitz1/sbml',
    'https://jjj.bio.vu.nl/rest/models/rohwer1/sbml',
    'https://jjj.bio.vu.nl/rest/models/rohwer2/sbml',
    'https://jjj.bio.vu.nl/rest/models/romond1/sbml',
    'https://jjj.bio.vu.nl/rest/models/rong1/sbml',
    'https://jjj.bio.vu.nl/rest/models/rong2/sbml',
    'https://jjj.bio.vu.nl/rest/models/rong3/sbml',
    'https://jjj.bio.vu.nl/rest/models/rovers1/sbml',
    'https://jjj.bio.vu.nl/rest/models/roy1/sbml',
    'https://jjj.bio.vu.nl/rest/models/saavedra/sbml',
    'https://jjj.bio.vu.nl/rest/models/saeidi1/sbml',
    'https://jjj.bio.vu.nl/rest/models/santolini1/sbml',
    'https://jjj.bio.vu.nl/rest/models/sarma1/sbml',
    'https://jjj.bio.vu.nl/rest/models/sarma2/sbml',
    'https://jjj.bio.vu.nl/rest/models/sarma3/sbml',
    'https://jjj.bio.vu.nl/rest/models/sarma4/sbml',
    'https://jjj.bio.vu.nl/rest/models/sarma5/sbml',
    'https://jjj.bio.vu.nl/rest/models/sarma6/sbml',
    'https://jjj.bio.vu.nl/rest/models/sarma7/sbml',
    'https://jjj.bio.vu.nl/rest/models/sarma8/sbml',
    'https://jjj.bio.vu.nl/rest/models/sarma9/sbml',
    'https://jjj.bio.vu.nl/rest/models/schaber/sbml',
    'https://jjj.bio.vu.nl/rest/models/schaber1/sbml',
    'https://jjj.bio.vu.nl/rest/models/scheper1/sbml',
    'https://jjj.bio.vu.nl/rest/models/schilling1/sbml',
    'https://jjj.bio.vu.nl/rest/models/schliemann1/sbml',
    'https://jjj.bio.vu.nl/rest/models/schoeberl/sbml',
    'https://jjj.bio.vu.nl/rest/models/schoeberl1/sbml',
    'https://jjj.bio.vu.nl/rest/models/sedaghat1/sbml',
    'https://jjj.bio.vu.nl/rest/models/sen1-2/sbml',
    'https://jjj.bio.vu.nl/rest/models/sengupta1/sbml',
    'https://jjj.bio.vu.nl/rest/models/sharp1/sbml',
    'https://jjj.bio.vu.nl/rest/models/shen1/sbml',
    'https://jjj.bio.vu.nl/rest/models/shen2/sbml',
    'https://jjj.bio.vu.nl/rest/models/shen3/sbml',
    'https://jjj.bio.vu.nl/rest/models/shenorr1/sbml',
    'https://jjj.bio.vu.nl/rest/models/shu1/sbml',
    'https://jjj.bio.vu.nl/rest/models/silva/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone0/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone1/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone10/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone11/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone12/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone13/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone14/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone15/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone16/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone17/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone18/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone19/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone2/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone20/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone21/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone22/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone23/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone3/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone4/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone5/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone6/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone7/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone8/sbml',
    'https://jjj.bio.vu.nl/rest/models/smallbone9/sbml',
    'https://jjj.bio.vu.nl/rest/models/snoep/sbml',
    'https://jjj.bio.vu.nl/rest/models/snoep1/sbml',
    'https://jjj.bio.vu.nl/rest/models/snoep2/sbml',
    'https://jjj.bio.vu.nl/rest/models/somogyi1/sbml',
    'https://jjj.bio.vu.nl/rest/models/somogyi2/sbml',
    'https://jjj.bio.vu.nl/rest/models/speirs1/sbml',
    'https://jjj.bio.vu.nl/rest/models/srimani1/sbml',
    'https://jjj.bio.vu.nl/rest/models/srivastava1/sbml',
    'https://jjj.bio.vu.nl/rest/models/srivastava2/sbml',
    'https://jjj.bio.vu.nl/rest/models/stafford1/sbml',
    'https://jjj.bio.vu.nl/rest/models/strasen1/sbml',
    'https://jjj.bio.vu.nl/rest/models/strasen10/sbml',
    'https://jjj.bio.vu.nl/rest/models/strasen11/sbml',
    'https://jjj.bio.vu.nl/rest/models/strasen2/sbml',
    'https://jjj.bio.vu.nl/rest/models/strasen3/sbml',
    'https://jjj.bio.vu.nl/rest/models/strasen4/sbml',
    'https://jjj.bio.vu.nl/rest/models/strasen5/sbml',
    'https://jjj.bio.vu.nl/rest/models/strasen6/sbml',
    'https://jjj.bio.vu.nl/rest/models/strasen7/sbml',
    'https://jjj.bio.vu.nl/rest/models/strasen8/sbml',
    'https://jjj.bio.vu.nl/rest/models/strasen9/sbml',
    'https://jjj.bio.vu.nl/rest/models/supplydemand/sbml',
    'https://jjj.bio.vu.nl/rest/models/supplydemand2/sbml',
    'https://jjj.bio.vu.nl/rest/models/tan1/sbml',
    'https://jjj.bio.vu.nl/rest/models/tang1/sbml',
    'https://jjj.bio.vu.nl/rest/models/teusink/sbml',
    'https://jjj.bio.vu.nl/rest/models/teusink2/sbml',
    'https://jjj.bio.vu.nl/rest/models/thomsen1/sbml',
    'https://jjj.bio.vu.nl/rest/models/thomsen2/sbml',
    'https://jjj.bio.vu.nl/rest/models/tiago1/sbml',
    'https://jjj.bio.vu.nl/rest/models/tiago2/sbml',
    'https://jjj.bio.vu.nl/rest/models/tiago3/sbml',
    'https://jjj.bio.vu.nl/rest/models/tripathi1/sbml',
    'https://jjj.bio.vu.nl/rest/models/twoenzymecompinh1/sbml',
    'https://jjj.bio.vu.nl/rest/models/twoenzymeparcompinh1/sbml',
    'https://jjj.bio.vu.nl/rest/models/twoenzymeparcompinh2/sbml',
    'https://jjj.bio.vu.nl/rest/models/twycross/sbml',
    'https://jjj.bio.vu.nl/rest/models/tyson10/sbml',
    'https://jjj.bio.vu.nl/rest/models/tyson11/sbml',
    'https://jjj.bio.vu.nl/rest/models/tyson12/sbml',
    'https://jjj.bio.vu.nl/rest/models/tyson13/sbml',
    'https://jjj.bio.vu.nl/rest/models/tyson14/sbml',
    'https://jjj.bio.vu.nl/rest/models/tyson2/sbml',
    'https://jjj.bio.vu.nl/rest/models/tyson3/sbml',
    'https://jjj.bio.vu.nl/rest/models/tyson4/sbml',
    'https://jjj.bio.vu.nl/rest/models/tyson5/sbml',
    'https://jjj.bio.vu.nl/rest/models/tyson6/sbml',
    'https://jjj.bio.vu.nl/rest/models/tyson7/sbml',
    'https://jjj.bio.vu.nl/rest/models/tyson8/sbml',
    'https://jjj.bio.vu.nl/rest/models/tyson9/sbml',
    'https://jjj.bio.vu.nl/rest/models/ueda1/sbml',
    'https://jjj.bio.vu.nl/rest/models/ung1/sbml',
    'https://jjj.bio.vu.nl/rest/models/uys/sbml',
    'https://jjj.bio.vu.nl/rest/models/valero/sbml',
    'https://jjj.bio.vu.nl/rest/models/vaneunen1/sbml',
    'https://jjj.bio.vu.nl/rest/models/vaneunen2/sbml',
    'https://jjj.bio.vu.nl/rest/models/vaneunen3/sbml',
    'https://jjj.bio.vu.nl/rest/models/vaneunen4/sbml',
    'https://jjj.bio.vu.nl/rest/models/vaneunen5/sbml',
    'https://jjj.bio.vu.nl/rest/models/vaneunen6/sbml',
    'https://jjj.bio.vu.nl/rest/models/vaneunen7/sbml',
    'https://jjj.bio.vu.nl/rest/models/vanheerden1/sbml',
    'https://jjj.bio.vu.nl/rest/models/vanheerden2/sbml',
    'https://jjj.bio.vu.nl/rest/models/veening1/sbml',
    'https://jjj.bio.vu.nl/rest/models/venturelli1/sbml',
    'https://jjj.bio.vu.nl/rest/models/venturelli2/sbml',
    'https://jjj.bio.vu.nl/rest/models/venturelli3/sbml',
    'https://jjj.bio.vu.nl/rest/models/venturelli4/sbml',
    'https://jjj.bio.vu.nl/rest/models/vernoux1/sbml',
    'https://jjj.bio.vu.nl/rest/models/vernoux2/sbml',
    'https://jjj.bio.vu.nl/rest/models/vilar1/sbml',
    'https://jjj.bio.vu.nl/rest/models/vilar2/sbml',
    'https://jjj.bio.vu.nl/rest/models/voit1/sbml',
    'https://jjj.bio.vu.nl/rest/models/wahl1/sbml',
    'https://jjj.bio.vu.nl/rest/models/wang/sbml',
    'https://jjj.bio.vu.nl/rest/models/wang1/sbml',
    'https://jjj.bio.vu.nl/rest/models/wang2/sbml',
    'https://jjj.bio.vu.nl/rest/models/wang3/sbml',
    'https://jjj.bio.vu.nl/rest/models/wegner1/sbml',
    'https://jjj.bio.vu.nl/rest/models/weimann1/sbml',
    'https://jjj.bio.vu.nl/rest/models/westerhoff1/sbml',
    'https://jjj.bio.vu.nl/rest/models/westermark/sbml',
    'https://jjj.bio.vu.nl/rest/models/whillier1/sbml',
    'https://jjj.bio.vu.nl/rest/models/whillier2/sbml',
    'https://jjj.bio.vu.nl/rest/models/whillier3/sbml',
    'https://jjj.bio.vu.nl/rest/models/whillier4/sbml',
    'https://jjj.bio.vu.nl/rest/models/wilhelm1/sbml',
    'https://jjj.bio.vu.nl/rest/models/wodarz1/sbml',
    'https://jjj.bio.vu.nl/rest/models/wodarz3/sbml',
    'https://jjj.bio.vu.nl/rest/models/wolf/sbml',
    'https://jjj.bio.vu.nl/rest/models/wolf2/sbml',
    'https://jjj.bio.vu.nl/rest/models/wortel1/sbml',
    'https://jjj.bio.vu.nl/rest/models/wortel2/sbml',
    'https://jjj.bio.vu.nl/rest/models/wortel3/sbml',
    'https://jjj.bio.vu.nl/rest/models/wortel4/sbml',
    'https://jjj.bio.vu.nl/rest/models/wu1/sbml',
    'https://jjj.bio.vu.nl/rest/models/xie1/sbml',
    'https://jjj.bio.vu.nl/rest/models/xu/sbml',
    'https://jjj.bio.vu.nl/rest/models/yamada1/sbml',
    'https://jjj.bio.vu.nl/rest/models/yamada2/sbml',
    'https://jjj.bio.vu.nl/rest/models/yang/sbml',
    'https://jjj.bio.vu.nl/rest/models/yao1/sbml',
    'https://jjj.bio.vu.nl/rest/models/yildirim1/sbml',
    'https://jjj.bio.vu.nl/rest/models/yugi1/sbml',
    'https://jjj.bio.vu.nl/rest/models/yugi2/sbml',
    'https://jjj.bio.vu.nl/rest/models/zatorskyc/sbml',
    'https://jjj.bio.vu.nl/rest/models/zatorskyd/sbml',
    'https://jjj.bio.vu.nl/rest/models/zatorskye/sbml',
    'https://jjj.bio.vu.nl/rest/models/zeilinger1/sbml',
    'https://jjj.bio.vu.nl/rest/models/zeilinger2/sbml',
    'https://jjj.bio.vu.nl/rest/models/zeilinger3/sbml',
    'https://jjj.bio.vu.nl/rest/models/zhao1/sbml',
    'https://jjj.bio.vu.nl/rest/models/zhu1/sbml',
    'https://jjj.bio.vu.nl/rest/models/zi1/sbml',
]

for i, each in enumerate(sbml_files):
    print(each)
    sbml_request = requests.get(each)
    sbml_request = sbml_request.json()
    for item in sbml_request:
        # print(sbml_request[item])
        with open('jws_models_test/' + item + '.xml', 'w') as model:
            model.write(sbml_request[item])

